<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.nexaticket</groupId>
    <artifactId>nexaticket-parent</artifactId>
    <version>0.1.0-SNAPSHOT</version>
  </parent>

  <artifactId>services</artifactId>
  <packaging>pom</packaging>
  <name>services</name>
  <description>Mỗi service = 1 bounded context = 1 database = 1 pipeline</description>

  <modules>
    <module>api-gateway</module>
    <module>identity-service</module>
    <module>ledger-service</module>
    <module>catalog-service</module>
    <module>inventory-service</module>
    <module>ordering-service</module>
    <module>realtime-gateway</module>
    <module>payment-service</module>
    <module>payout-service</module>
    <module>ticketing-service</module>
    <module>notification-service</module>
    <module>analytics-service</module>
  </modules>

  <dependencies>
    <!-- Mọi service đều có: web + actuator + model lỗi chuẩn -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>micrometer-registry-prometheus</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.nexaticket</groupId>
      <artifactId>shared-kernel</artifactId>
    </dependency>
    <dependency>
      <groupId>com.nexaticket</groupId>
      <artifactId>starter-web</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.nexaticket</groupId>
      <artifactId>starter-test</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <executions>
          <execution><goals><goal>repackage</goal></goals></execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
